language: node_js
node_js:
  - '7.0'
  - '6.0'
  - '5.0'
  - '4.0'
os:
  - linux
  - osx
after_script: NODE_ENV=test istanbul cover ./node_modules/mocha/bin/_mocha -- -R spec ./test/* && node node_modules/coveralls/bin/coveralls.js < coverage/lcov.info
